### ISSUE TITLE
Cannot uninstall plugin choicegroup

### ISSUE THREAD

**Issue by hartmut1s** [ndunand/moodle-mod_choicegroup#96] opened 2016-10-07 04:40 UTC
We have Moodle 3.1.1+ (Build: 20160811) installed. This morning I tried to update the plugin but I got stuck before I could update the Moodle database. Manually deleted the plugin.
Six hours later I did a fresh install of plugin choicegroup which went well. When I tried to uninstall the plugin at Site administration > Plugins > Plugins overview, I received the following error message:

core_plugin/err_cannot_uninstall_plugin
**Debug info:** core_plugin_manager::can_uninstall_plugin() returned false
Error code: err_cannot_uninstall_plugin
$a contents: Array
(
[plugin] => mod_choicegroup
)
**Stack trace:**
    line 84 of /admin/plugins.php: moodle_exception thrown

**Comment by ndunand** [comment] 2016-10-07 06:08
Hi, I just tried on Moodle 3.1.1 and couldn't reproduce.

If the plugin wasn't completely installed in the first place, it's normal Moodle can't uninstall it.

Do you have a more complete stack trace if possible.

**Comment by hartmut1s** [comment] 2016-10-07 06:41
Hi, thank you for your reply. I posted the complete error message. As I was able to manually uninstall the plugin and you couldn't replicate the issue, it's okay to close the issue. Just that you know: the update on October 5, 2016, went well. I was surprised to see another updated for group choice this morning (October 6). This update took very long and I had to stop it. If other people just do the latest update without the October 5 update, the process may be fine. Anyhow, I was able to uninstall the plugin.

**Comment by ndunand** [comment] 2016-10-07 07:01
Yes, the Oct. 5 update was released a bit too quickly, and one minor bug escaped my attention, hence the Oct. 6 update to correct it.

Thanks for your feedback. I also tried (just now) to reproduce your path, i.e. first install version from 10/5, then update to version from 10/6, then uninstall. All went without hiccups.

So, as you suggest, I'm closing this as we can't reproduce it.

**Closed by ndunand** 2016-10-07 07:01 UTC
