### ISSUE TITLE
Moodle 4.3 Compatible Version

### ISSUE THREAD

**Issue by michael-milette** [ndunand/moodle-mod_choicegroup#198] opened 2023-10-27 15:50 UTC
Hi @ndunand , 

Do you have any thoughts on when a Moodle 4.3 compatible version might become available?

Best regard,

Michael Milette

**Comment by michael-milette** [comment] 2023-10-28 01:10
In Moodle 4.3 (English) with PHP 8.2...

**When I select one of the groups, I see the following error message:**

Invalid event functions defined in \mod_choicegroup\event\choice_updated
line 275 of \lib\classes\event\base.php: call to debugging()
line 452 of \mod\choicegroup\lib.php: call to core\event\base::create()
line 155 of \mod\choicegroup\view.php: call to choicegroup_user_submit_response()

Script /moodle403/mod/choicegroup/view.php mutated the session after it was closed: $SESSION->editedpages
line 787 of \lib\classes\session\manager.php: call to debugging()
line 159 of \lib\classes\shutdown_manager.php: call to core\session\manager::check_mutated_closed_session()
line ? of unknownfile: call to core_shutdown_manager::shutdown_handler()

**When I view the report, I see the following error message:**

Invalid event functions defined in \mod_choicegroup\event\report_viewed
line 275 of \lib\classes\event\base.php: call to debugging()
line 74 of \mod\choicegroup\report.php: call to core\event\base::create()

**Comment by NicoAlexH** [comment] 2024-01-15 11:42
Hello @michael-milette, thanks for reporting ! 

I just tested the plugin under the same conditions (Moodle 4.3 + PHP 8.2) and everything is working fine : 
the warnings you got at the time might have been caused by the deprecated events removed in this commit : https://github.com/ndunand/moodle-mod_choicegroup/commit/1c03662d283f07714cbf2d10d13793ce4b7a26cb 

I am closing this issue for now, but feel free to reopen it if needed :)

**Closed by NicoAlexH** 2024-01-15 11:42 UTC
