### ISSUE TITLE
Restrict access by user fields is made fails and displays a blank page

### ISSUE THREAD

**Issue by Dextirpe** [ndunand/moodle-mod_choicegroup#94] opened 2016-09-27 06:56 UTC
Code modification "[Add new function choicegroup_get_responses and modify to choicegroup_… #90"](https://github.com/ndunand/moodle-mod_choicegroup/pull/90/commits/17c0bb60687cb47ab7dbb7ffa454bdf4df8a2638) 
It causes a blank page appears if access to the activity and have selected access restrictions with user profile field.
To resolve the error had to undo the last change of code described in the previous link

Error reported in developer mode:
Notice: Undefined offset: 4447 in .../moodle/mod/choicegroup/lib.php on line 887 Fatal error: __clone method called on non-object in .../moodle/mod/choicegroup/lib.php on line 887

My Moodle version is 3.0.6 and I have installed the last choicegroup 1.9.1 for Moodle 2.7-3.1 (Build: 2016090500)

**Comment by cmathieu11** [comment] 2016-11-14 08:34
Hello,
we have the same error on a Moodle 3.1.2+ (Build: 20160923)

- Undefined offset: 178314 in /data/moodle/mod/choicegroup/lib.php on line 895
- Fatal error: __clone method called on non-object in /data/moodle/mod/choicegroup/lib.php on line 895
Is it possible, to temporarily resolve the error, to undo the last change of code as suggested below ?
Thanks a lot for your job on this plugin.
Christophe

**Comment by NicoAlexH** [comment] 2021-06-30 12:15
Hello, 
it's a bit late but we can't reproduce the bug, therefore we'll close this issue but feel free to reopen it / reply if you still encounter it.

**Closed by NicoAlexH** 2021-06-30 12:15 UTC
Labels: bug
