### ISSUE TITLE
Group choice: Show Group member

### ISSUE THREAD

**Issue by p0pp3** [ndunand/moodle-mod_choicegroup#121] opened 2019-01-07 17:38 UTC
Hello

the "Show Group members" button doesn't seem to work after upgrading to moodle 3.5.

Could you please update the plugin to support this feature again?

best regards
Simon

**Comment by barry-matthias** [comment] 2019-01-10 10:53
Selecting either the "Show group members" or selecting the "Show descriptions" throws a javascript error as per the following debug trace output from the browser dev tools
![ceplus_jscript_error](https://user-images.githubusercontent.com/21336311/50963935-f56a2d80-14c5-11e9-9715-ffd7ba8c3a15.png)

**Comment by ndunand** [comment] 2019-01-10 12:50
Hi can you tell me if you are using a third-party theme? This has been tested in theme boost on Moodle 3.5 and 3.6.

**Comment by barry-matthias** [comment] 2019-01-10 14:18
Hi
We also tested it with the clean theme and the current boost theme with the same result of the jscript error. The debug output above was generated using the clean theme but we have also tested using snap and boost themes with the same result.

this is the version of the module we are currently using
1.15 for Moodle 2.7-3.5 (Build: 2018070900)

**Comment by barry-matthias** [comment] 2019-01-10 14:30
Hi

Also tested it in chrome the debug gives a little more information as per below:

javascript.js:2 Uncaught TypeError: Cannot read property 'focus' of undefined
 
tested using Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by ndunand** [comment] 2019-01-10 14:31
Hi,

Strange that I can't reproduce.

Anyway can you try and remove lines 36-43 from https://github.com/ndunand/moodle-mod_choicegroup/blob/master/javascript.js#L36 ?

These lines are at fault and are not really functionally necessary.

**Comment by barry-matthias** [comment] 2019-01-10 14:32
Hi
Unfortunately i am not able to change the code as we can only run on release versions, you should get some communications soon with our developers at Blackboard regarding this too hopefully make the required changes.

regards and thanks
Barry Matthis

**Comment by ndunand** [comment] 2019-01-10 14:35
Alright, as I can't reproduce I'll leave it as is until further communication.
Cheers

**Comment by miotto** [comment] 2019-01-10 23:36
Hi
The file javascript.js is no longer used, see commit b0f298f (19 Jun 2018). Will not the file choicegroupdatadisplay.js be used now?

@barry-matthias 
Maybe you do not use the latest version?

Cheers

**Comment by pavelsokolov** [comment] 2019-01-28 09:43
This hits us as well. We're using Moodle Analytics tool and enabling piwik results in the following error. Only occurs in group choice module.

![image](https://user-images.githubusercontent.com/3234777/51827013-76645a00-22f9-11e9-9101-24b5bfcb8f6d.png)

**Comment by Rabecerra** [comment] 2019-02-04 19:50
Hi guys, 
I'm talking in behavior of Blackboard, in our code base we still had the Javascript call in renderer.php file so that is causing the issue. We are going to update mod_choicegroup to fix this. I think you can close this issue.

**Comment by ndunand** [comment] 2019-02-05 06:33
@Rabecerra thanks for reporting back. OK I'll close the issue once I've cleaned up the unused JavaScript.

**Closed** 2021-07-16 06:36 UTC
