### ISSUE TITLE
Ability to register in full groups

### ISSUE THREAD

**Issue by Atlasfreak** [ndunand/moodle-mod_choicegroup#226] opened 2024-10-14 19:03 UTC
When sending a request to join a full group there is a quite high possibility to actually get added to the full group.
This is possible by sending the request through a different choicegroup where the groups aren't limited.

**Comment by ndunand** [comment] 2024-10-15 06:19
Hello and thanks for reporting this. This is probably what we want by design though. As you're stating the limits are not inherent to the groups themselves but to the selectable options form the Group Choice activities themselves. Therefore if one of these activities offer registering to a group with no limit (or a higher limit) to another activity, there would be no good way to enforce this.
Closing this for now. Feel free to reopen if needed.

**Closed by ndunand** 2024-10-15 06:19 UTC
